config/routes.rb
ToolingApi::Application.routes.draw do
  resources :apex_classes

end

app/models/apex_class.rb
require 'restforce'
class ApexClass < Restforce::SObject
	include ActiveModel::Validations
	include ActiveModel::Conversion
	extend  ActiveModel::Naming
end

app/controllers/apex_classes_controller.rb
class ApexClassesController < ApplicationController
  #comment the below method until i figure out how to implement it
  before_action :set_apex_class, only: [:edit, :update, :destroy]

  # GET /apex_classes
  # GET /apex_classes.json
  def index
    @apex_classes = sfdc_client.query "SELECT Id, Name FROM ApexClass"
  end

  ## Show method isn't really necessary here
  #
  # GET /apex_classes/1
  # GET /apex_classes/1.json
  # def show
  #   @apex_class = Restforce.tooling(SalesforceUtility.init_args).find("ApexClass", params[:id])
  # end

  # GET /apex_classes/new
  def new
    @apex_class = ApexClass.new
    @apex_class_body = ''
  end

  # GET /apex_classes/1/edit
  def edit
    @apex_class_body = CGI.unescape(@apex_class.Body)
  end

  # POST /apex_classes
  # POST /apex_classes.json
  def create
    @apex_class = ApexClass.new(apex_class_params)

    respond_to do |format|
      if @apex_class.save
        format.html { redirect_to @apex_class, notice: 'Apex class was successfully created.' }
        format.json { render action: 'show', status: :created, location: @apex_class }
      else
        format.html { render action: 'new' }
        format.json { render json: @apex_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apex_classes/1
  # PATCH/PUT /apex_classes/1.json
  def update
    respond_to do |format|
      if @apex_class.update(apex_class_params)
        format.html { redirect_to @apex_class, notice: 'Apex class was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @apex_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apex_classes/1
  # DELETE /apex_classes/1.json
  def destroy
    @apex_class.destroy
    respond_to do |format|
      format.html { redirect_to apex_classes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apex_class
      # @apex_class = ApexClass.find(params[:id])
      @apex_class = sfdc_client.find("ApexClass", params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apex_class_params
      params[:apex_class]
    end

    def sfdc_client
      sfdc_init_args = YAML.load_file('config/salesforce.yml')[Rails.env]
      Restforce.tooling(sfdc_init_args)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/salesforce_utility.rb
module SalesforceUtility
	def self.init_args
    YAML.load_file("config/salesforce.yml")[Rails.env]
	end
end

class Restforce::SObject
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend  ActiveModel::Naming

  def to_param
    self.Id
  end

  def to_key
  	[self.Id]
  end

  def id
  	self.Id
  end
  
  def is_persisted?
  	!(self.Id.class == NilClass)
  end

  def self.model_name
  	ApexClass
  end
end

app/helpers/apex_classes_helper.rb
module ApexClassesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/apex_classes/_form.html.erb
<%= form_for(@apex_class, url: new_apex_class_path) do |f| %>

  <div class="actions">
    <%= f.submit "Compile" %>
  </div>


  <% if @apex_class.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@apex_class.errors.count, "error") %> prohibited this apex_class from being saved:</h2>
      render!

      <ul>
      <% @apex_class.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <textarea id="editor" cols="100" rows="40">
      <%= @apex_class_body %>
    </textarea>
  </div>

  <div class="actions">
    <%= f.submit "Compile" %>
  </div>

<% end %>

app/views/apex_classes/edit.html.erb
<h1>Editing: <%= @apex_class.Name %> </h1>

<%= render 'form' %>

<%= link_to 'Show', @apex_class %> |
<%= link_to 'Back', apex_classes_path %>

app/views/apex_classes/index.html.erb
<h1>Listing apex_classes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @apex_classes.each do |apex_class| %>
      <tr>
        <td><%= apex_class.Name %><td>
        <td><%= link_to 'Edit', edit_apex_class_path(apex_class) %></td>
        <td><%= link_to 'Destroy', apex_class, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Apex class', new_apex_class_path %>

app/views/apex_classes/new.html.erb
<h1>New apex_class</h1>

<%= render 'form' %>

<%= link_to 'Back', apex_classes_path %>

app/views/apex_classes/show.html.erb
<p id="notice"><%= notice %></p>
<div>
	<textarea cols="100" rows="40">
		<%= CGI.unescape(@apex_class.Body) %>
	</textarea>
</div>

<%= link_to 'Edit', edit_apex_class_path(@apex_class) %> |
<%= link_to 'Back', apex_classes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToolingApi</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
   <%= stylesheet_link_tag    "/codemirror-3.12/lib/codemirror.css", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "/codemirror-3.12/lib/codemirror.js", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "/codemirror-3.12/mode/clike/clike.js", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  



  
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

  <script>
	// myTextArea = document.getElementById('editor');
 // //  	var myCodeMirror = CodeMirror.fromTextArea(myTextArea);
 // 	var myCodeMirror = CodeMirror(function(elt) {
	//   myTextArea.parentNode.replaceChild(elt, myTextArea);
	// }, {value: myTextArea.value});


  var editor = CodeMirror.fromTextArea(document.getElementById("editor"), {
    lineNumbers: true,
    matchBrackets: true,
    mode: "text/x-java"
  });
    
  </script>
</body>
</html>